# Generated by Django 3.2.4 on 2021-06-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_investment_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('return_per', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
            ],
        ),
    ]
