# Generated by Django 3.2.4 on 2021-06-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('field1', models.CharField(max_length=50)),
                ('field2', models.CharField(max_length=50)),
                ('field3', models.CharField(max_length=50)),
            ],
        ),
    ]
