# Generated by Django 3.2.4 on 2021-06-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_type',
            field=models.CharField(choices=[('Business', 'Business Loans'), ('Checking', 'Checking accounts'), ('Savings', 'Savings accounts'), ('Cards', 'Debit and Credit Cards'), ('Insurance', 'Life Insurance')], default='Business', max_length=50),
        ),
    ]
