# Generated by Django 3.2.4 on 2021-06-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_services_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_type',
            field=models.CharField(choices=[('BUSINESS', 'Business Loans'), ('CHECKING', 'Checking accounts'), ('SAVINGS', 'Savings accounts'), ('CARDS', 'Debit and Credit Cards'), ('INSURANCE', 'Life Insurance')], default='Business', max_length=50),
        ),
    ]
