# Generated by Django 3.2.4 on 2021-06-06 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myCards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('transaction_id', models.CharField(max_length=15)),
                ('transaction_type', models.CharField(choices=[('NONE', 'None'), ('SHOPPING', 'Shopping'), ('TRANSER', 'Transfer'), ('SERVICE', 'Service')], default='NONE', max_length=15)),
                ('transaction_date', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt', models.FileField(upload_to='')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myCards.addcard')),
            ],
        ),
    ]
