# Generated by Django 3.2.4 on 2021-06-15 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='transaction_category',
            field=models.CharField(choices=[('NONE', 'None'), ('DEBIT', 'Debit'), ('CREDIT', 'Credit')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='transactions',
            name='transaction_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('UNSUCCESSUL', 'Unsuccessful')], default='PENDING', max_length=15),
        ),
        migrations.AddField(
            model_name='transactions',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='receipt',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(choices=[('NONE', 'None'), ('SHOPPING', 'Shopping'), ('TRANSFER', 'Transfer'), ('SERVICE', 'Service')], default='NONE', max_length=15),
        ),
    ]
