# Generated by Django 3.2.4 on 2021-06-15 09:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transactions_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
