# Generated by Django 3.2.4 on 2021-06-06 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_type', models.CharField(choices=[('CHOOSE', 'Choose one option'), ('PERSONAL LOANS', 'Personal Loans'), ('CORPORATE LOANS', 'Corporate Loans'), ('BUSINESS LOANS', 'Business Loans'), ('CUSTOM LOANS', 'Custom Loans')], default='CHOOSE', max_length=20)),
                ('left_to_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(max_length=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('installment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
