# Generated by Django 3.2.4 on 2021-06-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='loan_type',
            field=models.CharField(choices=[('CHOOSE', 'Choose one option'), ('Personal_Loans', 'Personal Loans'), ('Coorporate_Loans', 'Corporate Loans'), ('Business_Loans', 'Business Loans'), ('Custom_Loans', 'Custom Loans')], default='CHOOSE', max_length=20),
        ),
    ]
