# Generated by Django 3.2.4 on 2021-06-10 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myCards', '0005_auto_20210610_1427'),
        ('loans', '0002_alter_loans_loan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myCards.addcard'),
            preserve_default=False,
        ),
    ]
