# Generated by Django 3.2.4 on 2021-06-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcard',
            name='card_type',
            field=models.CharField(choices=[('NONE', 'None'), ('CLASSIC', 'Classic'), ('SECONDARY', 'Secondary')], max_length=15),
        ),
    ]
