# Generated by Django 3.2.4 on 2021-06-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCards', '0003_alter_addcard_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcard',
            name='card_type',
            field=models.CharField(choices=[('NONE', 'None'), ('CLASSIC', 'Classic'), ('SECONDARY', 'Secondary')], default='NONE', max_length=15),
        ),
    ]
