# Generated by Django 3.2.4 on 2021-06-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCards', '0004_alter_addcard_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcard',
            name='card_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='addcard',
            name='expense',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='addcard',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='addcard',
            name='total_saving',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
